name: Tests

on:
  push:
    tags: v*.*.*

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: autotest
    steps:
      - name: Start
        run: |
          cd C:\actions-runner\autotest\
          .\AutomaticTesting.exe -all

