name: Deploy Web

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:bastyon
        
      - name: Prepare archive
        run: |
          mkdir /tmp/bastyon
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /tmp/bastyon/
          tar czf /tmp/bastyon.tgz -C /tmp/bastyon .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bastyon.tgz
          path: /tmp/bastyon.tgz

  deploy:
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ web.1, web.2, web.3 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: bastyon.tgz
      - name: Unpack artifact
        run: tar xzf bastyon.tgz -C /data/gui/ --no-same-owner
      - name: Reset nginx cache
        run: /data/reset_cache.sh
        shell: bash
