name: Deploy Web

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:brighteon -- -sha=${{ github.sha }}
        
      - name: Prepare archive
        run: |
          mkdir /tmp/brighteon
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /tmp/brighteon/
          tar czf /tmp/brighteon.tgz -C /tmp/brighteon .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: brighteon.tgz
          path: /tmp/brighteon.tgz

  deploy:
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ btio1, btio2, btio3 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: brighteon.tgz
      - name: Unpack artifact
        run: tar xzf brighteon.tgz -C /home/bastyon/.bastyon.gui --no-same-owner
      - name: Delete artifacts
        run: rm -rf brighteon.tgz
      - name: Reset nginx cache
        run: /data/reset_cache.sh
        shell: bash
