name: Deploy to pre.pocketnet.app

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: gui 

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:bastyon

      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','package-lock.json','minimize.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/pre/
