name: Deploy to pre.pocketnet.app

on:
  push:
    tags: v*.*.*

  workflow_dispatch:

jobs:
  build:
    runs-on: gui 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:bastyon

      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git/','.github/','node_modules/'} ./ /docker/pre/
